blank_issues_enabled: false
contact_links:
  - name: ğŸ“ƒ Ninja Documentation
    url: https://github.com/szapp/Ninja
    about: Documentation of Ninja.
  - name: â” Questions and Problems
    url: https://github.com/szapp/patch-template/discussions
    about: Please ask and answer questions here.
